// Auto-generated by scripts/generate-skills.ts — do not edit

export const bundledSkills: Record<string, string> = {
  "a2ui-generation": `---
name: a2ui-generation
description: Design and generate official A2UI v0.9 \`updateComponents\` and \`updateDataModel\` payloads for three modes: DTO component, non-DTO component, and non-DTO page. Use when asked to create or refine A2UI cards, components, or pages from DTO/JSON/business data, generate Python transformer code for DTO-driven components, iterate on existing A2UI output files by diff, improve mobile UI quality, or validate A2UI rules such as \`surfaceId\`, component id \`root\`, path binding, and component-vs-page boundaries.
---

# A2UI Generation

## What This Skill Does

- Generate or refactor A2UI \`updateComponents\` and \`updateDataModel\`
- Output a unified Python transformation entry in \`DTO Component\` mode
- Iterate on existing files rather than rewriting everything from scratch each round
- Gate quality through design review and validation scripts

## Execution Boundary

- Do not proactively search, read, borrow from, or imitate historical examples, old artifacts, sample pages, sample JSON, sample HTML, or screenshot outputs in the repository unless the user explicitly requests it
- By default, rely only on the user's current input, currently attached files, and this skill's own documentation
- If the user provides a DTO, do not hard-code business facts

## First Principle: User Requirements First

- Global first principle: \`User requirements first\`
- When a feature explicitly requested by the user conflicts with a skill default rule, prioritize the user requirement
- Do not "pretend to comply with the skill"; explicitly record the conflict and apply a targeted exemption during the validation phase
- Exemptions are scoped only to items the user explicitly requested — never use them as an excuse to disable validation globally
- Choose an appropriate layout style based on the user's requirements and intent; using the same layout style and color scheme across multiple queries is forbidden

## Query / Search Term Scenario Detection

Before entering mode selection, determine whether the user input is an **information summary card** scenario:

**Trigger conditions**: The user provides a natural language search query, place name, person name, event name, or concept word (e.g., "Snow in the Forbidden City", "West Lake", "Su Dongpo") and asks for an information card.

**⚠️ CRITICAL WARNING — English model content inflation risk**: When generating cards for query/search-term inputs in English, there is a strong model tendency to produce article-style content with long paragraphs, full narrative sections, and detail-page structures. This is **always wrong** for summary cards. Treat every word below as a hard constraint, not a suggestion.

**Mandatory card shape for this scenario (non-negotiable)**:
- Structure locked to: \`Title → Core attributes (1–3) → Brief summary (≤ 2 lines) → Tag group → Optional CTA\`
- Main sections ≤ 3
- Body text ≤ 2 paragraphs; each paragraph ≤ 3 lines
- **FORBIDDEN**: Dynamic \`List\` child templates (i.e., \`children.componentId\`-driven template rows such as \`tips_item_template\`) — this is a detail-page structure, not a summary card
- **FORBIDDEN**: Full-width hero image (\`aspect-ratio: 16/9 + width: 100%\`) — this is a page header, not a card element
- **FORBIDDEN**: Expanding the card into an article or content detail page (multiple long body paragraphs + full lists)
- Total card height must not exceed 2/3 of screen height

**Canonical layout patterns** (choose one; do not invent new structures):
- \`Horizontal summary card\`: small thumbnail on the left + title / core metrics / tags / CTA on the right (suitable for POIs, attractions, products)
- \`Vertical summary card\`: title section at top + core metrics row (2–3 numeric metrics side by side) + one-line summary + tags + CTA (suitable for events, people, concepts)

**Pre-generation self-check (mandatory before writing any JSON)**:
- [ ] Main sections ≤ 3?
- [ ] No dynamic List sub-templates?
- [ ] No full-width hero image?
- [ ] Body paragraphs ≤ 2, each ≤ 3 lines?
- [ ] Total height within 2/3 screen?
If any item fails → converge first or escalate to page explicitly. Never bypass.

## Output Format for Chat Agent

Only emit official A2UI v0.9 protocol messages in the payload. The payload must be \`createSurface\`, \`updateComponents\`, \`updateDataModel\`, \`deleteSurface\`, or a list of those messages.

在聊天中输出一个完整的 \`agenui\` 围栏代码块：

\`\`\`agenui
{
  "type": "agenui",
  "payload": {
    "version": "v0.9",
    "updateComponents": {
      "surfaceId": "card",
      "components": [...]
    },
    "updateDataModel": {
      "surfaceId": "card",
      "path": "/data",
      "value": {...}
    }
  }
}
\`\`\`

App 会剥离 \`{ type: "agenui", payload: ... }\` 包装，将 \`payload\` 渲染为 A2UI 卡片气泡。普通对话用文字回复，仅在需要结构化 UI 时使用 \`agenui\`。

## Mode Selection

Before starting, determine:
1. Does the user want a \`component/card\` or a \`full page\`?
2. Has the user provided a DTO?

Default to generating a component / card for the user, unless the user explicitly says they want a full page.

Then enter exactly one of the following three modes:

### Mode 1: DTO Component

Applicable when:
- The user has provided a DTO
- The user wants a component / card

Deliverables:
1. Python transformer code
2. \`updateComponents\` JSON
3. \`updateDataModel\` JSON

Unified entry function:
\`\`\`python
def build_component_payload_from_dto(dto: dict) -> tuple[dict, dict]:
    ...
\`\`\`

### Mode 2: Non-DTO Component

Applicable when:
- The user has not provided a DTO
- The user wants a component / card

Deliverables:
1. \`updateComponents\` JSON
2. \`updateDataModel\` JSON

Mandatory order (must not be reversed):
1. Output UI layout (\`updateComponents\`) first
2. Output data (\`updateDataModel\`) second

### Mode 3: Non-DTO Page

Applicable when:
- The user has not provided a DTO
- The user wants a full page

Deliverables:
1. \`updateComponents\` JSON
2. \`updateDataModel\` JSON

Mandatory order (must not be reversed):
1. Output UI layout (\`updateComponents\`) first
2. Output data (\`updateDataModel\`) second

Supplementary rules:
- Only the three modes above are defined by default
- If the user provides a DTO but explicitly wants a full page, do not silently apply one of these modes; ask first whether to design the page as DTO-driven

## Read Only What You Need

Do not read all sub-documents by default. Load only what the current task requires:

| Task type | Required docs | Load on demand |
| --- | --- | --- |
| DTO component | [\`docs/dto-component-mode.md\`](docs/dto-component-mode.md), [\`docs/component-design.md\`](docs/component-design.md) | [\`docs/component-catalog.md\`](docs/component-catalog.md), [\`docs/data-binding.md\`](docs/data-binding.md), [\`docs/visual-interaction.md\`](docs/visual-interaction.md) |
| Non-DTO component | [\`docs/component-catalog.md\`](docs/component-catalog.md), [\`docs/component-design.md\`](docs/component-design.md) | [\`docs/data-binding.md\`](docs/data-binding.md), [\`docs/visual-interaction.md\`](docs/visual-interaction.md) |
| Non-DTO page | [\`docs/component-catalog.md\`](docs/component-catalog.md), [\`docs/page-design.md\`](docs/page-design.md), [\`docs/visual-interaction.md\`](docs/visual-interaction.md) | [\`docs/data-binding.md\`](docs/data-binding.md), [\`docs/review-validation.md\`](docs/review-validation.md) |
| Bug fix / review / iterating on existing artifacts | [\`docs/review-validation.md\`](docs/review-validation.md) | Whichever doc is directly related to the issue |

Additional notes:
- Load [\`docs/component-catalog.md\`](docs/component-catalog.md) when you need to verify atomic components, charts, fields, allowed values, or style whitelists
- Load [\`docs/data-binding.md\`](docs/data-binding.md) when you need to verify path binding, template binding, or relative path rules
- Load [\`docs/component-design.md\`](docs/component-design.md) when you need to verify component height budgets, card content budgets, or multi-column text budgets
- Load [\`docs/page-design.md\`](docs/page-design.md) when you need to verify full-page structure, layout composition, or page-level sectioning

## Workflow

1. Read user input; confirm mode, data source, interaction requirements, and visual constraints
2. Load only the sub-documents the current task truly needs
3. Before formal output, explicitly list the layout rationale: at minimum describe the main sections, visual focal point, information rhythm, key horizontal relationships, and the role of images
4. Based on that layout rationale, draft an internal first version, then perform at least \`1\` explicit design improvement before proceeding to formal output
5. Output the first draft formally in an \`agenui\` fenced code block
6. At delivery, if placeholder links were used, explicitly remind the user to replace them

## Non-Negotiables

Only truly irreplaceable business invariants that scripts cannot fully substitute are listed here:

- Non-DTO mode must produce UI layout (\`updateComponents\`) before data (\`updateDataModel\`)
- Do not output fake buttons; clickable elements must use a real \`Button + action\`
- Real buttons must have visible label text; do not rely solely on \`variant\` to guess the runtime background color
- DTO fields must pass a semantic validity check before display; non-empty does not equal informative
- When semantic meaning depends on a combination of fields (e.g., status + time), perform the combination mapping first, then decide whether to display or omit
- \`Component/card\` mode must not silently become page-like; do not deliver a near-full-screen large card
- Component mode content should converge first; escalate to page only when convergence fails, and do so explicitly
- **Card hard gate (self-check before generating any JSON)**: main sections ≤ 3; no dynamic \`List\` sub-templates (i.e., \`children.componentId\`-driven template rows); no full-width hero image (\`aspect-ratio: 16/9 + width: 100%\`); body paragraphs ≤ 2; if any item fails, converge first or escalate to page explicitly — bypassing is not allowed
- **Information summary card scenario (query/search-term driven)**: structure is locked to \`Title → Core attributes (1–3) → Brief summary (≤ 2 lines) → Tag group → CTA\`; expanding into article narrative structure is forbidden
- **Tag group and CTA must be in separate rows**: when a card bottom has both a tag group (>= 2 tags) and a CTA button, they must be separated using Column (tag row first, CTA below); placing them in the same Row is forbidden — even flex-wrap and flex-shrink cannot prevent the CTA from overflowing and being clipped
- **⚠️ English model content inflation guard**: When query input is in English, the model tends to generate long-form article content. For every card task, actively resist generating: multiple long body paragraphs, full visitor tip lists, narrative sections, or any structure that resembles a detail page. If you find yourself writing more than 2 paragraphs of body text, stop and converge immediately
- A single card defaults to one main card shell; a full visual shell (\`background + border-radius + drop-shadow\`) inside a \`Card\` is forbidden
- A row of multiple images defaults to \`Row + flex\` fill; downgrade to a horizontal scroll container (\`List direction=horizontal\`) only when narrow-screen clipping risk is real
- Protected content — short phrases, CTAs, rating values, prices, times — must not wrap or fragment due to a fixed narrow width
- \`CTA\` buttons default to content-driven width via \`padding + border-radius\`; do not write a fixed narrow width unless explicit alignment requirements exist and readability has been verified
- When design requires images, do not fabricate non-existent image URLs
- Before formal output, the layout rationale must be explicitly listed; skipping layout planning and jumping straight to JSON is not allowed
- The layout rationale must cover at minimum: main sections, visual focal point, content rhythm, key component relationships, and the role of images/charts
- Before formal output, at least \`1\` explicit improvement round is required; the first version in your head must not be delivered directly as the final first draft
- This explicit improvement round defaults to prioritizing premium feel, design quality, and overall completeness — not just literal additions

## Resources

- Sub-document index: [\`reference.md\`](reference.md)
- Component catalog: [\`docs/component-catalog.md\`](docs/component-catalog.md)
- Data binding: [\`docs/data-binding.md\`](docs/data-binding.md)
- DTO mode: [\`docs/dto-component-mode.md\`](docs/dto-component-mode.md)
- Component design: [\`docs/component-design.md\`](docs/component-design.md)
- Page design: [\`docs/page-design.md\`](docs/page-design.md)
- Visual & interaction: [\`docs/visual-interaction.md\`](docs/visual-interaction.md)
- Review & validation: [\`docs/review-validation.md\`](docs/review-validation.md)
- Validation script: [\`scripts/validate_a2ui.py\`](scripts/validate_a2ui.py)
`,
  "amap-lbs": `---
name: amap-lbs
description: 高德地图 LBS 能力，包括关键词搜索、附近搜索、路线规划、智能旅行规划。当用户需要找地点、查路线、规划行程时使用。
---

# 高德地图 LBS 能力

## 可用工具

### search_nearby — 附近搜索
搜索用户当前位置周边的兴趣点（POI），支持关键词过滤。

### plan_route — 路线规划
从用户当前位置到目的地的路线规划，支持：
- **步行** (walking): 适合短距离徒步，显示详细步行指引
- **驾车** (driving): 适合自驾游，提供多条路线选择
- **骑行** (riding): 适合骑行路线
- **公交** (transit): 公共交通方案，含换乘指引

### plan_travel — 智能旅行规划
根据用户位置和偏好，自动生成一日游/多日游行程安排。

## 使用策略

### 找地点
用户说"附近有什么""帮我找厕所""哪里有餐厅"→ 调用 search_nearby，设置合适的关键词和半径。

### 查路线
用户说"怎么去XX""从这里到XX多远"→ 先确认目的地坐标（可通过 search_nearby 搜索获得），然后调用 plan_route。
- 徒步场景默认用步行模式
- 长距离可建议驾车或公交

### 规划行程
用户说"帮我安排一天""有什么推荐路线"→ 调用 plan_travel，根据用户偏好设置主题和时长。

## 注意事项
- 所有地图功能需要高德 Web服务 API Key
- 未配置 Key 时，告知用户去设置页填写
- 坐标使用 GCJ-02 坐标系（高德标准）
- 距离和时间仅供参考，实际可能因路况不同
`,
  "hiking-guide": `---
name: hiking-guide
description: 当用户想出去走走、询问附近有什么、需要轻松路线或陪伴聊天时使用。这是走走搭子的核心行为模式。
---

# 走走搭子“小 Pi”

你是一位轻松、可靠、熟悉附近生活的散步搭子。你的名字叫小 Pi。

## 性格
- 像一个愿意陪用户下楼走走的朋友，亲近但不打扰
- 关注日常场景：下班、饭后、周末、等人、换换心情
- 语气轻松自然，不要把普通散步说成登山、远足或专业户外活动
- 关心用户的安全、体力、天气和回程便利

## 主动行为
当用户想“出去走走”或询问附近时：
1. 调用 get_location 获取当前位置
2. 调用 search_nearby 搜索附近适合顺路看看的地方
3. 根据搜索结果，用 2-3 句话给出轻松、可执行的建议
4. 如果用户想要路线，再调用 plan_route 规划步行路线

## 推荐偏好
- 优先推荐公园、河边、街区、咖啡店、书店、便利店、安静小路、生活服务点
- 关注距离、步行时间、是否绕路、是否容易返回
- 夜间优先推荐明亮、人多、交通方便的路线
- 天气不好时提醒带伞、避开积水或建议改成室内附近逛逛

## 讲解风格
- 控制在 3-5 句话，用户可以继续追问
- 多用日常语言，少用专业户外术语
- 不确定的地点、历史或路线要直接说明，不要编造
- 可以顺手给一点情绪价值，比如“这条路适合放空一下”

## 禁止行为
- 不要默认用户要去山里、景区或长距离徒步
- 不要推荐你不确定存在的地点或路线
- 不要忽视夜间、天气、交通和偏僻路段的风险
`,
  "location-narrator": `---
name: location-narrator
description: 当需要根据用户当前位置讲解周围环境时使用。包括到达新地点、用户问"这里有什么"等场景。
---

# 位置感知讲解

## 工作流程

1. 调用 get_location 获取精确坐标和地址
2. 调用 search_nearby 搜索半径 1km 内的 POI
3. 调用 get_weather 获取当前天气（如果尚未获取）
4. 综合信息，生成讲解

## 讲解内容层次

### 即时环境（50m 范围）
- 当前所在的地形：山脊、溪谷、林间、草地
- 明显的地标：大石头、古树、溪流
- 当前海拔和坡度（如果 GPS 精度足够）

### 周边景点（1km 范围）
- 距离最近的 3-5 个兴趣点
- 每个用一句话概括
- 标注方向和步行时间

### 区域背景
- 所在山脉/景区的概况
- 海拔带和植被类型
- 当季特色（花季、红叶、雪景）

## 讲解格式

"📍 **[当前位置描述]**
海拔约 [X] 米 | [天气简述]

[2-3 句环境描述]

附近值得注意的：
- [景点1] — [方向+距离] — [一句话]
- [景点2] — [方向+距离] — [一句话]"
`,
  "photo-explainer": `---
name: photo-explainer
description: 当用户发送照片、拍照询问"这是什么"时使用。识别和讲解照片中的内容。
---

# 拍照讲解

## 识别流程

用户拍照后，按以下优先级识别和讲解：

### 植物
1. 识别到属/种级别（如果可以）
2. 通俗名 + 学名
3. 一句话特征描述（怎么认出它的）
4. 有趣的知识点（药用价值、民间传说、生态角色）
5. 安全提醒（如果有毒或会过敏）

### 动物
1. 识别物种
2. 行为解读（它可能在做什么）
3. 观察建议（保持距离、不要惊扰）
4. 如果是危险动物，立即提醒安全距离

### 建筑/遗迹
1. 先调用 get_location 获取位置上下文
2. 风格/年代判断
3. 历史/文化背景
4. 如果是知名景点，调用 search_nearby 获取更多信息

### 路标/指示牌
1. 读取内容
2. 解读含义
3. 对徒步的影响（方向、距离、警告）

### 地貌/地质
1. 地形类型判断（山谷、河床、岩壁等）
2. 成因简述（冰川、流水侵蚀、风化等）
3. 地质年代的想象类比

## 讲解模板

"这是一株 **[名称]**，你看它 [辨认特征]。
有趣的是，[知识点]。
[安全提醒（如果需要）]"

## 看不懂的情况

诚实回答："这个我不太确定，可能是 [猜测]，
但建议你用专业识别 App 确认一下。"
`,
  "safety-advisor": `---
name: safety-advisor
description: 当天气变化、地形险要、用户体力下降、或到达海拔较高区域时，主动提供安全建议。
---

# 安全建议

## 主动监测

### 天气变化
调用 get_weather 后发现以下情况时主动提醒：
- 降雨概率 > 60%：建议带雨具或考虑下撤
- 气温 > 35°C：提醒补水、防中暑
- 气温 < 5°C：提醒保暖
- 雷暴预警：立即建议避开空旷地带和高地
- 大风 > 6级：建议停止行进

### 地形安全
- 海拔 > 3000m：提醒高反风险，建议放慢节奏
- 检测到悬崖/陡坡路线：提醒注意脚下
- 溪流水位：雨后提醒可能涨水

### 时间安全
- 距日落 < 2 小时：提醒准备下山或扎营
- 当前不在已知步道上：提醒确认路线

## 提醒风格

不要大惊小怪，用关心的语气：
"注意一下，看起来下午可能有阵雨，咱们节奏可以稍微快点。"

而不是："警告！暴雨即将来临！立即寻找避难所！"

## 紧急情况

真正的紧急情况（受伤、迷路、雷暴）时：
1. 语气转为严肃
2. 给出具体行动建议
3. 提醒拨打紧急电话（110/119/120）
`,
  "trail-navigator": `---
name: trail-navigator
description: 当用户询问路线、迷路、或需要导航时使用。包括步道推荐、方向指引、距离估算。
---

# 路线导航

## 路线推荐

当用户问"往哪走"时：
1. 调用 get_location 获取当前位置
2. 调用 search_nearby 搜索附近的步道和路口
3. 根据用户情况推荐：
   - 体力好 + 时间充裕 → 推荐较长路线
   - 接近日落 → 推荐最短下山路线
   - 带小孩/老人 → 推荐平缓路线

## 方向指引

用通俗易懂的方式指路：
- ✅ "沿左手边的小路走约 200 米"
- ✅ "看到一块大石头后右转"
- ❌ "向东南方向行进 0.2 公里"

## 迷路处理

如果用户说迷路了：
1. 先安抚：别慌，咱们先确认位置
2. 调用 get_location
3. 分析位置：是否在已知步道附近
4. 给出建议：
   - 在步道上 → 指引回主路
   - 完全偏离 → 建议原路返回或原地等待
   - 有危险 → 建议拨打救援电话

## 距离和时间估算

基于地形类型估算徒步时间：
- 平路：4 km/h
- 爬升：海拔每升 300m 多算 30 分钟
- 下降：比平路慢 20%
- 体能一般：以上 × 1.3
`
};

export const bundledSkillDocs: Record<string, string> = {
  "a2ui-generation/docs/component-catalog.md": `# Component Catalog

## Protocol Shape

A2UI separates structure from data:
- \`updateComponents\`: component tree, layout, styles, binding paths
- \`updateDataModel\`: data content corresponding to binding paths
- Dynamic content is bound via \`{"path": "..."}\`

Minimal structure:

\`\`\`json
{
  "version": "v0.9",
  "updateComponents": {
    "surfaceId": "sample_surface",
    "components": [
      { "id": "root", "component": "Column", "children": ["title"] },
      { "id": "title", "component": "Text", "text": { "path": "/page/title" }, "variant": "h2" }
    ]
  }
}
\`\`\`

\`\`\`json
{
  "version": "v0.9",
  "updateDataModel": {
    "surfaceId": "sample_surface",
    "path": "/page",
    "value": {
      "title": "Hello A2UI"
    }
  }
}
\`\`\`

## Atomic Components

### Layout Components

#### \`Column\`

Stacks child components vertically.

\`\`\`json
{"id": "col1", "component": "Column", "children": ["child1", "child2"], "justify": "start|center|end|spaceBetween|spaceAround|spaceEvenly|stretch", "align": "start|center|end|stretch"}
\`\`\`

#### \`Row\`

Arranges child components horizontally.

\`\`\`json
{"id": "row1", "component": "Row", "children": ["child1", "child2"], "justify": "start|center|end|spaceBetween|spaceAround|spaceEvenly|stretch", "align": "start|center|end|stretch"}
\`\`\`

#### \`List\`

List component; supports static children or template rendering driven by dynamic data.

\`\`\`json
{"id": "list1", "component": "List", "children": ["item1", "item2"], "direction": "vertical|horizontal", "align": "start|center|end|stretch"}
\`\`\`

\`\`\`json
{"id": "list1", "component": "List", "children": {"path": "/data/items", "componentId": "item_template"}, "direction": "vertical|horizontal", "align": "start|center|end|stretch"}
\`\`\`

#### \`Card\`

Card container. \`child\` accepts only a single component id.

\`\`\`json
{"id": "card1", "component": "Card", "child": "inner_layout"}
\`\`\`

#### \`Tabs\`

Tab panel. \`tabs[].child\` is a component id.

\`\`\`json
{"id": "tabs1", "component": "Tabs", "tabs": [{"title": {"path": "/tabs/t1"}, "child": "tab_content_1"}, {"title": {"path": "/tabs/t2"}, "child": "tab_content_2"}]}
\`\`\`

#### \`Divider\`

Separator line.

\`\`\`json
{"id": "div1", "component": "Divider", "axis": "horizontal|vertical"}
\`\`\`

#### \`Modal\`

Dialog. \`trigger\` is the triggering component id; \`content\` is the dialog body component id.

\`\`\`json
{"id": "modal1", "component": "Modal", "trigger": "btn1", "content": "modal_body"}
\`\`\`

### Content Components

#### \`Text\`

\`\`\`json
{"id": "t1", "component": "Text", "text": {"path": "/data/title"}, "variant": "h1|h2|h3|h4|h5|body|caption"}
\`\`\`

#### \`RichText\`

Supported HTML tags: \`<b>\`, \`<i>\`, \`<u>\`, \`<br>\`, \`<blockquote>\`, \`<del>\`, \`<s>\`, \`<sub>\`, \`<sup>\`, \`<strong>\`, \`<em>\`, \`<code>\`, \`<a href="...">\`. \`linksEnable\` defaults to \`true\`.

\`\`\`json
{"id": "rt1", "component": "RichText", "text": {"path": "/data/richContent"}, "variant": "h1|h2|h3|h4|h5|body|caption", "linksEnable": true}
\`\`\`

#### \`Markdown\`

Supports common Markdown syntax and streaming incremental append.

\`\`\`json
{"id": "md1", "component": "Markdown", "content": {"path": "/data/mdContent"}}
\`\`\`

#### \`Image\`

\`\`\`json
{"id": "img1", "component": "Image", "url": {"path": "/data/imageUrl"}, "variant": "icon|avatar|smallFeature|mediumFeature|largeFeature|header", "fit": "contain|cover|fill|none|scale-down"}
\`\`\`

#### \`Icon\`

Built-in icon. \`name\` supports a literal value or \`{"path": "..."}\` dynamic binding.

\`\`\`json
{"id": "icon1", "component": "Icon", "name": "accountCircle|add|arrowBack|arrowForward|attachFile|calendarToday|call|camera|check|close|delete|download|edit|error|event|fastForward|favorite|favoriteOff|folder|help|home|info|locationOn|lock|lockOpen|mail|menu|moreHoriz|moreVert|notifications|notificationsOff|pause|payment|person|phone|photo|play|print|refresh|rewind|search|send|settings|share|shoppingCart|skipNext|skipPrevious|star|starHalf|starOff|stop|upload|visibility|visibilityOff|volumeDown|volumeMute|volumeOff|volumeUp|warning"}
\`\`\`

#### \`Video\`

\`\`\`json
{"id": "v1", "component": "Video", "url": {"path": "/data/videoUrl"}}
\`\`\`

#### \`AudioPlayer\`

\`\`\`json
{"id": "a1", "component": "AudioPlayer", "url": {"path": "/data/audioUrl"}, "description": {"path": "/data/audioDesc"}}
\`\`\`

#### \`Lottie\`

\`url\` supports \`http/https\`, \`res://...\`, \`file:///...\`. \`autoPlay\` defaults to \`true\`; \`loop\` defaults to \`true\`.

\`\`\`json
{"id": "lottie1", "component": "Lottie", "url": {"path": "/data/lottieUrl"}, "autoPlay": true, "loop": true, "variant": "icon|small|medium|large"}
\`\`\`

#### \`Web\`

\`source\` supports a URL or an HTML string.

\`\`\`json
{"id": "web1", "component": "Web", "source": {"path": "/data/webSource"}}
\`\`\`

### Interaction Components

#### \`Button\`

\`child\` accepts only a single component id. \`action\` supports \`functionCall\` or \`event\`.

\`\`\`json
{"id": "btn1", "component": "Button", "child": "btn_text1", "variant": "primary|borderless", "action": {"functionCall": {"call": "openUrl", "args": {"url": "https://..."}}}, "style": {"background-color": "...", "border-radius": "...", "padding": "..."}}
\`\`\`

\`\`\`json
{"id": "btn2", "component": "Button", "child": "btn_text2", "action": {"event": {"name": "submit", "context": {"formId": "form1"}}}}
\`\`\`

#### \`TextField\`

\`\`\`json
{"id": "tf1", "component": "TextField", "label": {"path": "/data/tfLabel"}, "value": {"path": "/data/tfValue"}, "variant": "shortText|longText|number|obscured"}
\`\`\`

#### \`CheckBox\`

\`\`\`json
{"id": "cb1", "component": "CheckBox", "label": {"path": "/data/cbLabel"}, "value": {"path": "/data/cbChecked"}}
\`\`\`

#### \`ChoicePicker\`

\`\`\`json
{"id": "cp1", "component": "ChoicePicker", "label": {"path": "/data/cpLabel"}, "variant": "mutuallyExclusive|multipleSelection", "options": [{"label": {"path": "/data/opt1"}, "value": "v1"}, {"label": {"path": "/data/opt2"}, "value": "v2"}], "value": {"path": "/data/cpValue"}}
\`\`\`

#### \`Slider\`

\`\`\`json
{"id": "sl1", "component": "Slider", "label": {"path": "/data/slLabel"}, "min": 0, "max": 100, "value": {"path": "/data/slValue"}}
\`\`\`

#### \`DateTimeInput\`

\`\`\`json
{"id": "dt1", "component": "DateTimeInput", "label": {"path": "/data/dtLabel"}, "value": {"path": "/data/dtValue"}, "enableDate": true, "enableTime": true}
\`\`\`

### Chart Components

#### \`BarChart\`

\`\`\`json
{"id": "bc1", "component": "BarChart", "title": {"path": "/data/chartTitle"}, "data": {"path": "/data/chartData"}}
\`\`\`

\`data\` structure:

\`\`\`json
{"xAxis": ["Label1", "Label2"], "yAxis": ["Low", "Mid", "High"], "series": [{"name": "Series Name", "data": [{"value": 1.5, "label": "Display Text"}]}]}
\`\`\`

#### \`LineChart\`

\`\`\`json
{"id": "lc1", "component": "LineChart", "title": {"path": "/data/lineTitle"}, "data": {"path": "/data/lineData"}}
\`\`\`

#### \`DonutChart\`

\`\`\`json
{"id": "dc1", "component": "DonutChart", "title": {"path": "/data/donutTitle"}, "data": {"path": "/data/donutData"}}
\`\`\`

\`data\` structure:

\`\`\`json
{"series": [{"name": "", "data": [{"label": "Category A", "value": 30}, {"label": "Category B", "value": 70}]}]}
\`\`\`

#### \`Table\`

\`\`\`json
{"id": "tb1", "component": "Table", "columns": {"path": "/data/columns"}, "rows": {"path": "/data/rows"}}
\`\`\`

\`dataModel\` example:

\`\`\`json
{"columns": ["Name", "Age", "City"], "rows": [["Alice", "25", "New York"], ["Bob", "30", "London"]]}
\`\`\`

## Styles

### Common Styles

Common styles available on all atomic components:

\`\`\`json
"styles": {
  "width": "100px",
  "height": "100px",
  "padding": "20px 20px 20px 20px",
  "padding-inline-start": "10px",
  "padding-left": "10px",
  "padding-inline-end": "10px",
  "padding-right": "10px",
  "padding-block-start": "10px",
  "padding-top": "10px",
  "padding-block-end": "10px",
  "padding-bottom": "10px",
  "margin": "0px 0px 32px 0px",
  "margin-inline-start": "10px",
  "margin-left": "10px",
  "margin-inline-end": "10px",
  "margin-right": "10px",
  "margin-block-start": "10px",
  "margin-top": "10px",
  "margin-block-end": "10px",
  "margin-bottom": "10px",
  "background-color": "#FFFFFF",
  "border-radius": "32px",
  "border-color": "#E0E0E0",
  "border-style": "solid",
  "border-width": "1px",
  "opacity": 0.8,
  "overflow": "hidden|visible",
  "display": "none",
  "visibility": "visible|hidden",
  "flex-grow": 1,
  "flex-shrink": 1,
  "flex-wrap": "nowrap|wrap|wrap-reverse",
  "justify-content": "flex-start|flex-end|center|space-between|space-around|space-evenly",
  "align-items": "flex-start|flex-end|center|stretch|baseline",
  "align-content": "flex-start|flex-end|center|space-between|space-around|stretch",
  "align-self": "auto|flex-start|flex-end|center|stretch|baseline",
  "aspect-ratio": "16 / 9",
  "filter": "drop-shadow(0px 4px 16px rgba(0, 0, 0, 0.08))"
}
\`\`\`

Common style constraints:

- All size properties support \`px\` only
- \`padding\` / \`margin\` shorthand must use four values
- \`background-color\` supports \`#RRGGBB\`, \`#RRGGBBAA\`, \`rgb(...)\`, \`rgba(...)\`
- \`border-style\` supports only \`"solid"\`
- \`justify-content\` supports only \`flex-start|flex-end|center|space-between|space-around|space-evenly\`
- \`align-items\` supports only \`flex-start|flex-end|center|stretch|baseline\`
- \`flex-wrap\` supports only \`nowrap|wrap|wrap-reverse\`
- \`align-content\` supports only \`flex-start|flex-end|center|space-between|space-around|stretch\`
- \`align-self\` supports only \`auto|flex-start|flex-end|center|stretch|baseline\`
- \`overflow\` supports only \`hidden|visible\`
- \`display\` supports only \`"none"\`
- \`visibility\` supports only \`visible|hidden\`
- \`filter\` supports only \`drop-shadow(...)\`
- \`flex-basis\`, \`gap\`, \`box-shadow\`, \`position\`, \`z-index\` are not supported

### Text Styles

Text styles available on \`Text\` components only:

\`\`\`json
"styles": {
  "color": "#0E142B",
  "font-size": "16px",
  "font-weight": "normal|bold",
  "font-family": "sans-serif",
  "line-height": 1.3,
  "text-align": "left top|left|left center|left bottom|center top|center|center center|center bottom|right top|right|right center|right bottom",
  "line-clamp": 2,
  "text-overflow": "clip|head|middle|ellipsis",
  "text-decoration": "underline solid #FF0000",
  "text-decoration-line": "underline|line-through",
  "text-decoration-style": "solid|dashed",
  "text-decoration-color": "#FF0000",
  "text-decoration-thickness": "2px"
}
\`\`\`

Text style constraints:

- \`color\` supports only \`#RRGGBB\` or \`#RRGGBBAA\`
- \`font-weight\` supports only \`normal|bold\`
- \`line-height\` supports a multiplier or px; prefer multiplier for multi-line wrapping
- \`text-align\` supports only \`left top|left|left center|left bottom|center top|center|center center|center bottom|right top|right|right center|right bottom\`
- \`text-overflow\` supports only \`clip|head|middle|ellipsis\`, and requires \`line-clamp\`
- \`text-decoration-line\` supports only \`underline|line-through\`
- \`text-decoration-style\` supports only \`solid|dashed\`
- Text styles must not be applied to non-\`Text\` components

## Unified Font Scale

Font sizes must strictly use the following final output values:

- Global heading: \`40px\`
- Section title / secondary heading: \`36px\`
- Main content / secondary content / supporting content / table header / table data: \`32px\`
- Small text within cards: \`28px\`
- Tags / non-tag small labels / pills / footnotes: \`24px\`

POI scenario specific:

- POI name: \`32px\`
- Non-label text: \`28px\`
- Labels/tags: \`24px\`

Usage guidance:

- \`h1\` commonly uses \`40px\`
- \`h2\` / \`h3\` / section titles commonly use \`36px\`
- Normal body text, descriptions, table content start at \`32px\`
- Weaker supporting info commonly uses \`28px\`
- Tags, badges, pills, footnotes should converge to \`24px\`
`,
  "a2ui-generation/docs/component-design.md": `# Component Design

## Scope
This document covers \`component/card\` mode only, not full pages.

## Height Boundary
- \`Component/card\`: defaults to no more than \`1/3\` of page height
- A card is a summary-type container, not a miniaturized page

Do not expand using a page-level structure and then try to compress the height afterward.

## Card Content Budget
In card mode, defaults should be:
- Only one core conclusion area or primary visual focal point
- Only one group of the most critical supporting info
- Only one primary CTA or main status action area
- Typically no more than \`2–3\` main sections

Content that should not be placed in a card by default:
- Long lists
- Long tables
- Long timelines
- Long explanatory text
- Multiple large parallel sections
- Full page-level narrative chains

### Information Summary Card — Dedicated Rules (Query / Search-Term Scenario)
When the query is a search term, place name, person name, event name, or concept word, the card is an **information summary card**. The following additional rules are mandatory:

**English model content inflation warning**: English language models tend to produce article-style, detail-page content for these queries. Every rule below is a hard constraint — not a default preference that can be overridden by "making it richer."

**Hard content budget (non-negotiable upper limits)**:
- Body text ≤ 2 paragraphs; each paragraph ≤ 3 lines
- Dynamic \`List\` sub-templates (\`children.componentId\`-driven rows such as \`tips_item_template\`): **FORBIDDEN** — this is a detail-page structure
- Full-width hero image (\`aspect-ratio: 16/9 + width: 100%\`): **FORBIDDEN** — this is a page header element, not a card element
- Main sections ≤ 3
- Total card height must not exceed 2/3 of screen height

**Required structure**:
\`\`\`
Title section (title + optional subtitle)
↓
Core attributes row (2–3 key metrics, laid out horizontally)
↓
Brief summary (Text component, ≤ 2 lines)
↓
Tag group (Row + multiple Text tag elements)
↓
CTA button (optional)
\`\`\`

**Anti-patterns (must avoid)**:
- Multiple long body paragraphs (5+ lines each) + full visitor tips list + full-width hero image = article detail page, NOT a summary card
- \`List\` + \`componentId\` dynamic sub-template rendering = detail-page data-driven list, NOT a summary card
- Any structure where you could replace the card with a news article and it would still make sense = you have gone too far

For DTO component mode, additional rules apply:
- When a secondary field is missing, prefer omitting the corresponding component rather than leaving an empty placeholder
- When a key field for an entire section is missing, prefer omitting the entire section
- The final card should remain complete and compact — missing fields must not leave visible blank gaps
- When text length is uncertain, the structure must leave room for wrapping, truncation, and fallback layouts

## Card Escalation Rule
Treat any of the following as exceeding the card budget:
- Even after compression, the card fills or nearly fills a full screen
- More than \`3\` main sections are needed to convey the information
- The primary information requires continuous vertical scrolling to be fully seen
- After removing secondary content, the card is still too tall, too full, or too fragmented

The correct response is:
1. Converge to a summary-type card
2. If convergence still does not hold, escalate to a page
3. Do not silently deliver a page-sized large card and call it a "component"

## Mobile Width Safety
A2UI targets mobile narrow screens by default. When generating cards, avoid horizontal overflow first.

General principles:
- Do not put long text, long institution names, navigation paths, or body summaries in side-by-side multi-column structures
- Do not rely on "text being just short enough" to maintain layout
- Horizontal layouts are better suited for short labels, short numbers, button groups, and icon combinations
- When content length is uncertain, prefer \`Column\` or \`List\`
- If a local area naturally suits horizontal browsing and cannot be fully contained on a narrow screen, allow that local area to scroll horizontally to reveal more

Supplementary notes:
- "Prefer \`Column\`" is the default conservative strategy — it does not mean abandoning design quality
- If a local section clearly suits left-right opposition, dual-side tension, or information juxtaposition, do not downgrade it to plain vertical stacking just to be safe
- The correct approach is to first judge whether the horizontal relationship holds, then decide whether wrapping or reflow is needed

## Competitive Layouts
When a local section naturally suits layouts like "core metric left / supporting info right", "main visual left / description right", or "left-right aligned", design it as a competitive horizontal layout — not a plain left-to-right concatenation.

Goal:
- When space allows, left and right sides form tension and order
- Only when genuine competition occurs should wrapping, truncation, or vertical reflow be introduced
- Do not let a column break spontaneously due to container modeling errors when there is no actual competition

In A2UI's current capabilities, runtime breakpoints, \`min-width\`, \`flex-basis\`, or text measurement for precise decisions are not available, so heuristic decisions must be made at generation time.

Recommended flow:
1. First identify whether this section is "left-right opposition" rather than "plain horizontal concatenation"
2. Define the role and minimum readable form for each column
3. Try to preserve the left-right anchor relationship first, then let weak information absorb compression
4. Only switch to wrapping or vertical structure when heuristic judgment clearly shows real competition

## Protected Column Readability
A protected column must not just be "visible" — it must maintain minimum readable form.

Rules:
- Do not give a protected column an excessively narrow fixed width that causes its internal text to wrap into \`2–3\` lines even when there is no competition
- If a caption / unit label / supporting phrase in this column should be fully readable but is forced to break by a fixed width that is too small, this is a layout error, not valid responsive behavior
- First ensure core numbers, main status, and key phrases are displayed completely before compressing other columns

For short phrases:
- Short phrase captions should by default remain as complete word groups — do not split them into ugly broken lines
- If this column cannot hold both the core number and the phrase, prioritize reallocating column widths, adjusting information hierarchy, or rewriting the local structure
- Do not let the protected column collapse first, then misattribute the problem to "competition with the right side"

## Short CJK Phrase Integrity
Short CJK phrases, short CTAs, and short numeric phrases are high-risk break candidates by default — "broken but still visible" is not an acceptable result.

Content treated as protected by default:
- \`2–8\` character short phrases, e.g. "Book Now", "Open", "Patio View"
- Numeric phrases, e.g. \`4.9\`, \`¥268\`, \`22:30\`
- Number-plus-phrase, e.g. "Reputation 986+", "Today 30% off", "Avg. ¥268"
- Short status labels and rating summaries next to icons

Mandatory requirements:
- Do not let such content wrap character-by-character, hang a single character, or leave punctuation on its own line due to a fixed narrow width
- Do not split "Book Now" into "Book / Now", or break \`4.9\`, \`22:30\`, \`¥268\` into fragments
- If the phrase is in a button column, rating column, status column, price column, or right-side action column, default to protecting its integrity
- If the phrase's integrity and the current layout cannot coexist, fix the layout first — do not accept fragmented typography

Priority order:
1. Widen the protected column
2. Move, downgrade, or push weak information to the next line
3. Adjust local structure hierarchy
4. Only then consider truncating weak information

Do not mistake "short CJK phrase breaking first" for normal responsive behavior — it typically signals incorrect column width allocation.

## CTA Width Policy
A \`CTA\` button is a protected column — do not default to a narrow fixed width just for the sake of alignment.

Default strategy:
- Buttons prefer \`padding + border-radius\` for volume; do not write a fixed \`width\` first
- Short CTA text should naturally stretch the button width via content
- If a button sits alongside a long description, let the description absorb compression rather than letting the button text break first
- If the button label is a short phrase, do not accept character-by-character wrapping or a \`2x2\` grid-style layout

Only consider a fixed width when:
- The visual system explicitly requires equal-width button groups
- Alignment with other fixed-width sibling modules is required
- The fixed width has been verified to keep button text fully readable

If a fixed width is required:
- Estimate based on "minimum readable form" first — do not start with a visually appealing number
- Account for large font sizes, horizontal padding, and icon space when computing the width budget
- If the fixed width causes the button text to wrap before the description column does, treat it as a layout error and revert

## Multi-Column Text Budget
When adopting a multi-column layout for premium feel, do not let all columns compete for width without limits.

Assign a role to each column first:
- Protected column: core numbers, main status, primary button, key visuals, avatars/thumbnails, core badges
- Compressible column: descriptive text, supporting descriptions, secondary labels, supplementary notes, source attribution

Handling principles:
- Protected columns take priority for complete visibility — do not let long text squeeze them out
- Compressible columns absorb shrinkage first
- Long text defaults to wrapping first
- Use \`line-clamp\` only if wrapping still clearly breaks the layout
- Truncation should occur on weak information — do not truncate main titles, core status, or key CTAs first
- Do not mistake "the protected column itself is too narrow and breaks" for appropriate wrapping
- If the horizontal relationship holds, preserve left-right alignment first, then decide which column absorbs compression
- If this is plain concatenation rather than true left-right opposition, do not assume you have completed a premium horizontal layout

Implementation strategy:
- Give visual columns, number columns, and button columns stable width or stronger layout priority
- Give text columns higher compressibility, e.g. allow \`flex-shrink\`
- Text columns prefer multiple lines rather than forcing everything on one line
- Secondary descriptions, footnotes, source attributions, and supplementary labels can use \`line-clamp: 1–2\`
- If the main title must be truncated, first confirm no lower-priority content is competing for width on the same line
- If a row contains an image, badge, long title, and supporting text simultaneously, do not force all of them into a single horizontal layer
- For "left metric / right description" layouts, prefer left-right anchoring, strong-vs-weak column division, and wrapping when necessary — not mechanical concatenation of a fixed small left block and a plain right list
- For button columns, rating columns, and status columns, default to avoiding narrow fixed widths; when content includes short phrases or numeric phrases, natural width or a larger budget is even more important

Anti-patterns:
- Right-side CTA with a fixed narrow width, causing "Book Now" to split into two lines or four squares
- Rating column simultaneously carrying star icon, score, and summary, with a narrow fixed width causing \`4.9\` or "Reputation 986+" to fragment
- Left-side long description still fully expanded while the right-side protected column — rating or button — breaks first
- **Tag group and CTA button placed in the same Row, causing the CTA to be pushed outside the card's right boundary and clipped invisible**

## Tag Group and CTA Layout Isolation Rule

**FORBIDDEN: Placing a tag group and a CTA button inside the same Row.**

This is the most common root cause of button overflow and clipping. When there are >= 2 tags, even if you set flex-wrap: wrap and flex-grow: 1 on the tag group, and flex-shrink: 0 on the CTA, if the total tag width + CTA width > card width, the CTA will still overflow the card's right boundary and be clipped invisible.

Reason: **flex-wrap only controls wrapping among direct children inside that container — it has no effect on sibling nodes (like cta_button) in the outer Row.**

Typical wrong structure (forbidden — no flex property can fix this):
\`\`\`
bottom_row (Row, justify: spaceBetween)
├── tag_group (Row, flex-grow: 1, flex-wrap: wrap) ← expands to fill remaining space
│   ├── tag_c9 / tag_stem / tag_public
└── cta_button (flex-shrink: 0) ← pushed outside right boundary, clipped invisible
\`\`\`

**Correct structure (mandatory)**: Separate tag group and CTA into independent rows using Column:
\`\`\`
bottom_section (Column)
├── tag_row (Row, justify: start, flex-wrap: wrap)
│   ├── tag_1 / tag_2 / tag_3
└── cta_button (margin-top: 12px, width: 100%)
\`\`\`

**Only exception**: When there is exactly 1 tag with very short text (<= 4 chars) and overflow has been confirmed not to occur, same-row placement may be considered. Otherwise, always use separate rows.

## Evidence Vs Badge
Do not turn semantically different information into the same type of small block.

How to differentiate:
- Badge / tag / pill: short words, short phrases, weak decorative info — suitable for capsule/pill style
- Evidence / supporting sentence: sentence-level proof, credible corroboration, supplementary explanation — defaults to a supporting info column, not a badge wall

Rules:
- Sentence-level evidence should not default to heavy rounded-corner blocks — avoid making the supporting area a secondary visual center
- If the right side carries supporting evidence, prefer presenting it as an ordered supporting info area, not a group of competing mini-cards
- To strengthen hierarchy, prefer arrangement, whitespace, font size, and color layering — not a pile of independent colored blocks adding visual weight

## Card Shell Guidance
- A single card defaults to one main card shell
- Use lightweight sectioning inside the main card — no card-within-card
- If \`Card\` is already used as the main shell, its immediate children must not add a full visual shell (\`background-color + border-radius + drop-shadow\`)
- \`root\` handles layout only — do not assign card background to it
- Small cards need appropriate whitespace on the outside — borders and shadows must not touch the edge
- If the card body uses a prominent \`drop-shadow(...)\`, outer whitespace must not be a token amount
- Cards should be composable content blocks, not standalone panels with an outer background plate

## Missing Data Behavior
For missing fields in DTO component mode, the default behavior should be "structural pruning", not "style hiding":
- Missing text field: omit the corresponding text component
- Missing image field: omit the corresponding image component and its wrapper
- Missing badge / tag field: omit the corresponding badge area
- Missing entire info group: omit the entire section

The goal is for the final structure to be naturally compact — not held together by empty values, empty containers, or hidden styles.

## Image Strip Fill Rule
When a card needs "multiple images in a row" and the images are the primary visual, fill must be prioritized over mere visibility.

Mandatory requirements:
- In an image strip that needs to fill horizontally, prefer letting \`Row\` carry \`Image\` directly — do not wrap in an extra \`Card\` or container by default
- \`Image\` defaults to \`fit: cover\` — avoid thumbnails floating in large empty slots
- Do not use \`variant\` (e.g. \`smallFeature\`, \`mediumFeature\`) on \`Image\` in a fill strip, as the renderer may apply built-in sizes that prevent filling the parent layout
- A2UI style sizes support \`px\` only — do not use \`%\`, \`vw\`, or similar units to express fill

Recommended implementation:
- Image strip container: default to \`Row\` (fill-style primary visual); switch to \`List(direction=horizontal)\` only when narrow-screen clipping risk is real
- Image component: plain \`Image\`
- Image style: at minimum include a uniform \`height\` (px) + \`flex-grow: 1\` + \`flex-shrink: 1\` + necessary border-radius/clipping styles
- Spacing: use \`margin\` (four values) to control gaps between image items

Standard non-scrolling image strip (preferred):
\`\`\`json
{"id": "image_strip", "component": "Row", "children": ["image_0", "image_1", "image_2"], "align": "stretch"}
{"id": "image_0", "component": "Image", "url": {"path": "/card/images/0"}, "fit": "cover", "styles": {"height": "220px", "flex-grow": 1, "flex-shrink": 1, "margin": "0px 8px 0px 0px", "border-radius": "18px", "overflow": "hidden"}}
\`\`\`

Standard horizontal-scroll image strip (fallback):
\`\`\`json
{"id": "image_strip", "component": "List", "children": ["image_0", "image_1", "image_2"], "direction": "horizontal", "align": "start"}
{"id": "image_0", "component": "Image", "url": {"path": "/card/images/0"}, "fit": "cover", "styles": {"width": "312px", "height": "252px", "margin": "0px 12px 0px 0px", "border-radius": "20px"}}
\`\`\`

Selection strategy (mandatory):
1. Use \`Row + Image(fit: cover) + flex-grow/flex-shrink\` for a fill row first (default)
2. If this causes static clipping on the target narrow screen, the last image gets swallowed, or the visible width is clearly insufficient, switch to \`List(horizontal)\` (fallback)
3. Do not default to horizontal scrolling just because there are multiple images — scrolling is a risk mitigation, not a default style

## Compatibility Driven Layout
Because the DTO component Python will handle more DTOs of the same type, the component structure itself must also be compatible:
- Do not build layout on the assumption that "every field happens to exist and every text happens to be short"
- Explicitly layer fields into required / optional
- Design the layout-collapse path for when optional fields are missing
- For high-volatility fields like main title, subtitle, institution name, source, and tags, prepare multi-line or truncation strategies by default
`,
  "a2ui-generation/docs/data-binding.md": `# Data Binding

## Core Rules
- \`updateComponents\` contains only structure, not concrete business values
- Dynamic values always use binding paths
- All binding paths use \`/\` as the separator, never dot notation

## Absolute Path Binding
Example:
\`\`\`json
{"id": "t1", "component": "Text", "text": {"path": "/page/title"}}
\`\`\`

\`\`\`json
{"updateDataModel": {"path": "/page", "value": {"title": "Hello World"}}}
\`\`\`

Rules:
- Absolute paths must use \`/\` as the separator, e.g. \`/page/title\`
- Do not write \`/page.title\`
- Nested fields also use \`/\`, e.g. \`/fuelCard/labels/availableLiters\`

## Dynamic Template Binding
Both \`List\` and \`Column\` can drive child components from data. Template components use relative paths internally.

\`\`\`json
{"id": "list1", "component": "List", "children": {"path": "/data/items", "componentId": "item_tpl"}}
{"id": "item_tpl", "component": "Text", "text": {"path": "name"}}
\`\`\`

\`\`\`json
{"updateDataModel": {"path": "/data/items", "value": [{"name": "Item A"}, {"name": "Item B"}]}}
\`\`\`

Relative path rules:
- Simple field: \`name\`
- Nested field: \`labels/availableLiters\`
- Do not write \`labels.availableLiters\`

## Advanced Component List Binding
For protocol-level compatibility understanding: list-type attributes in advanced components typically use a string path directly, and element field mapping uses relative paths:

\`\`\`json
{"component": "", "items": "/cg/items", "itemTitle": {"path": "title"}}
\`\`\`

Common list-type attribute names:
- \`items\`
- \`cards\`
- \`contents\`
- \`segments\`
- \`tips\`
- \`tags\`

## updateDataModel Shape
Standard structure:
\`\`\`json
{
  "version": "v0.9",
  "updateDataModel": {
    "surfaceId": "sample_surface",
    "path": "/root_path",
    "value": {}
  }
}
\`\`\`

Rules:
- \`path\` must start with \`/\`
- \`path\` must not use dot notation
- \`value\` must be semantically consistent with \`path\`

## Binding Reminders
- Design the component tree first, then map data — do not hard-code values into components
- List templates prefer relative paths — do not write array element fields as absolute paths
- Any occurrence of \`/foo.bar\` or \`labels.availableLiters\`-style paths is an error
`,
  "a2ui-generation/docs/dto-component-mode.md": `# DTO Component Mode

## Scope
This document covers \`DTO Component\` mode only.

## When to Use
- The user has provided a DTO (data transfer object)
- The user wants a component / card (not a full page)

## Deliverables
1. Python transformer code (\`*_transformer.py\`)
2. \`updateComponents\` JSON
3. \`updateDataModel\` JSON

## Unified Entry Function
All Python transformers must use this entry point:

\`\`\`python
def build_component_payload_from_dto(dto: dict) -> tuple[dict, dict]:
    """
    Args:
        dto: raw data transfer object (dict)

    Returns:
        tuple of (updateComponents_dict, updateDataModel_dict)
    """
    ...
\`\`\`

## DTO Discipline

### Required vs Optional Fields
- Explicitly layer fields into required / optional
- Design the layout-collapse path for when optional fields are missing
- When a secondary field is missing, prefer omitting the corresponding component rather than leaving an empty placeholder
- When a key field for an entire section is missing, prefer omitting the entire section
- The final card should remain complete and compact — missing fields must not leave visible blank gaps

### Semantic Validity Check
- DTO fields must pass a semantic validity check before display; non-empty does not equal informative
- When semantic meaning depends on a combination of fields (e.g., status + time), perform the combination mapping first, then decide whether to display or omit
- Low-information-value fields (generic / section words) should be filtered or downgraded

### Compatibility
- The Python must be compatible with more DTOs of the same type, not just tailored to one sample
- Do not build layout on the assumption that "every field happens to exist and every text happens to be short"
- When text length is uncertain, the structure must leave room for wrapping, truncation, and fallback layouts

## Common Combined Fields
- \`openStatus/openStatusCode/status/openTime/*\` should be combined into readable status copy, not single-field output
`,
  "a2ui-generation/docs/page-design.md": `# Page Design

## Scope
This document covers \`full page\` mode only, not components/cards.

## Page Boundary
- \`Full page\`: defaults to at least \`2–3\` screens
- A page should contain multiple content sections, not just a stretched card

## Page Structure
A full page typically combines multiple sections using \`Column\`, with \`Divider\` in between:

\`\`\`json
{
  "id": "root",
  "component": "Column",
  "children": ["section1", "divider1", "section2", "divider2", "section3"]
}
\`\`\`

A page should typically have:
- A clear main heading area
- At least \`2–3\` content sections
- Clear information hierarchy
- A rhythm that allows continuous downward scrolling, not one huge content block

## Page-Only Content
The following content is better suited for pages than cards:
- Long lists
- Long tables
- Long timelines
- Multiple large parallel sections
- Full narrative chains
- Multi-paragraph explanatory text

## Page Layout Guidance
- Pages can have richer sectioning, rhythm, and visual transitions
- Do not mechanically apply a three-column statistics card template to the page summary area
- Multiple sections are allowed inside a page, but each section should still have clear hierarchy
- If local horizontal information truly suits horizontal browsing, a local horizontal scroll container can be used
- Do not make the entire page's main content area require horizontal scrolling to be fully seen

## Pre-Output Layout Planning
Before formally outputting \`updateComponents\`, explicitly write out a layout rationale. Do not jump directly to generating JSON.

This pre-output layout rationale must answer at minimum:
- What main sections will the page have
- What is the visual focal point of the first screen / hero
- How the information rhythm unfolds: hook first, then explain, then expand, then close
- Which relationships suit horizontal spread, which should scroll vertically
- What roles images, charts, route ribbons, and timelines each play

Recommended minimal template:
1. \`Page skeleton\`
   - Example: \`hero -> atmosphere guide -> main schedule -> evening closing -> practical info -> CTA\`
2. \`Visual focal point\`
   - Example: first screen builds impact through large image; mid-section builds premium feel through whitespace and headings; closing section uses a softer accent color
3. \`Information rhythm\`
   - Example: overview first, then expand Day 1/Day 2, then evening scenery mood and practical reminders
4. \`Key layout relationships\`
   - Example: timeline with fixed info on the left and flexible copy on the right; route overview as a full ribbon, not easily-squeezed chip strings

## Explicit Improvement Before Formal Output
After completing the layout rationale above, do not directly deliver the first version as formal output. At least one explicit improvement round is required, and it must explain:
- What is not premium enough / not complete enough / not well-designed in the first version
- What the second version intends to strengthen
- Whether the improvement is reflected in layout, visual focal point, rhythm, palette, and information hierarchy — not just rewriting a few lines of copy

Default priority for improvement:
- Remove template feel; strengthen overall page coherence
- Improve premium feel and refinement, not just stacking more components
- Optimize the transition between the first screen and subsequent sections
- Optimize the primary/secondary relationship between images and text
- Optimize the presentation of routes, times, CTAs, and other high-risk horizontal information

## Page Escalation Reminder
If the user originally wanted only a component/card, but the content clearly requires:
- Multiple main sections
- Continuous vertical scrolling
- Multi-paragraph narrative explanation
- Long lists or long tables

Then explicitly suggest: this is better suited for \`page\` mode.
`,
  "a2ui-generation/docs/review-validation.md": `# Review Validation

## Purpose
This document unifies the review and validation process after a first draft, with the goal of:
1. Removing prose-like stacking; improving layout and visual quality
2. Ensuring readability, tappability, and usability on small screens
3. Passing both script and model validation without violating user requirements

## End-to-End Flow
After the first draft is written to disk, execute the following flow by default:
1. Read the on-disk file (review based on file, do not start a new draft)
2. Run the script validation (\`scripts/validate_a2ui.py\`)
3. If it fails, fix the original file directly and re-run until it passes
4. Only after the script passes for the first time, begin model design review and continue optimizing via diff
5. At least \`1\` model review round; if the output is still plain / prose-like / has risks, do another \`2nd\` round
6. If the model review modifies files, re-run the script validation; if it fails, continue fixing until it passes again
7. Only after the script passes and model review is complete can delivery happen

## Round Checklist (Every Round)
Check the following universal items every round:
- Has the mode been clearly identified: \`DTO Component\` / \`Non-DTO Component\` / \`Non-DTO Page\`
- Can all data paths be found in the \`dataModel\`
- Are any banned advanced components, unsupported style properties, or non-reproducible hard-coded values used
- Do lists use template capability rather than hard-coded repeated components
- Is the layout clearly distinct from plain text stacking (not just "one row after another")
- Are atomic component capabilities being fully used to express hierarchy and emphasis
- Was the layout rationale explicitly stated before formal output, rather than skipping planning and going straight to generation
- Was at least \`1\` explicit design improvement completed before formal output
- At \`360px\` width, does any overflow, horizontal blowout, or primary information invisibility occur
- Are buttons visible and readable (text contrasts sufficiently with background, does not rely on \`variant\` to guess background color)
- Do images come from user materials or genuinely verifiable sources (no fabricated URLs)
- Do font sizes comply with the specification
- Are there any high-risk break candidates: short phrases, short CTAs, rating values, times, prices
- For full pages: is there obvious "collage-style" color palette jumping? Do the hero, main body sections, and night/chart/CTA areas belong to the same color band system

## Page Palette Review
When the task is \`Non-DTO Page\`, after the script first passes, perform an additional "page palette coherence focused review":
1. Ignore images; look only at component background colors, text colors, button colors, and tag colors
2. Judge whether the page looks like one cohesive work, not multiple templates stitched together
3. Focus checks:
   - Does the \`hero\` / heading disconnect from the rest of the page body
   - Is there a back-and-forth jump: "dark hero -> pure white mid-section -> dark night section -> dark CTA"
   - Has the accent color proliferated into multiple hues
   - Do \`chart\`, \`night\`, \`cta\` sections truly need a full dark background
4. If jarring transitions exist, fix in the following priority order:
   - Unify the full-page base color band
   - Pull dark sections back to a light-background expression
   - Reduce the number of accent colors
   - Finally, preserve one necessary dark opening area if absolutely needed

Experience thresholds:
- The full page defaults to allowing at most \`1\` clear dark opening area
- If the \`hero\` is already dark, avoid multiple independent dark large sections after it
- If the user has not explicitly requested strong contrast, default to "unified" over "contrasting"

## Mode-Specific Checks

### For \`Component/Card\` (DTO + Non-DTO)
- Is height within the single-screen \`1/3\` budget, avoiding page-sized large cards
- Are main sections converged to \`2–3\` or fewer; is primary info focused enough
- Is there a double card shell: \`Card\` outer shell exists, and inner layer adds another full visual shell
- In multi-column rows, are "protected columns" distinguished from "compressible columns"
- Do captions / unit labels / short phrases in protected columns maintain minimum readable form
- Do sections that should be left-right opposed actually anchor both sides, rather than plain concatenation
- Is there "no real competition but breaks first" (e.g. initial width budget error causing pseudo-wrapping)
- Is there "left description still full, right CTA / rating / status breaks first" — priority inversion
- Are short CTA text, rating values, times, prices, and status words being squeezed into fragments by narrow fixed-width containers
- Is the fixed-width button truly necessary; if just for alignment, should it revert to content-driven width
- Is supporting evidence over-cardsified, causing focal point fragmentation
- For multiple images in a row: is \`Row + flex\` fill tried first; only downgrading to \`List(direction=horizontal)\` when narrow-screen clipping risk is real
- Is horizontal scrolling used only for local horizontal consumption areas, not for main content areas

## Protected Content Wrap Review
For any horizontal layout, during the model review phase after the script first passes, perform an additional "protected content abnormal wrapping focused review":
1. List the protected content in the current section:
   - CTA label text
   - Status words / short badges
   - Rating values / prices / times
   - Short descriptions next to icons
2. Verify each item:
   - Is it in a narrow fixed-width container
   - Could character-by-character wrapping, single-character hanging, or punctuation on its own line occur
   - Does the protected column break first, before weak information compresses
3. If the answer is "yes", fix in the following priority order:
   - Widen the protected column
   - Lower the priority of weak information or move it to the next line
   - Change to a left-right structure that better matches role assignment
   - Only then truncate weak information

Focused anti-patterns:
- Short CTAs like "Book Now" being cut into two lines by a narrow button
- Short values like \`4.9\`, \`22:30\`, \`¥268\` being compressed into fragments by fixed-width columns
- Left-side long description still fully expanded while the right-side rating column or button column has already broken

### For \`DTO Component\` Only
- Is the Python entry fixed as \`build_component_payload_from_dto\`
- Do \`*_components.json\` and \`*_datamodel.json\` come directly from running Python
- Are \`required\` and \`optional\` fields clearly distinguished
- Does missing a key field allow an explicit error, and does missing an optional field correctly degrade
- When a field is missing, is it handled via "omitting the component/section" rather than leaving an empty shell
- Are low-information-value fields (generic / section words) filtered or downgraded
- When semantic meaning depends on combined fields (e.g. business status), is combination modeling done before display
- Is Python compatible with more DTOs of the same type, not just tailored to one sample
- Are \`openStatus/openStatusCode/status/openTime/*\` combined into readable status copy, not single-field output

## Validation Script
Script location:
- [\`scripts/validate_a2ui.py\`](scripts/validate_a2ui.py)

Common invocations:
- \`python scripts/validate_a2ui.py components.json datamodel.json\`
- \`python scripts/validate_a2ui.py combined.md\`
- \`python scripts/validate_a2ui.py components.json datamodel.json overrides.json\`
- \`python scripts/validate_a2ui.py combined.md overrides.json\`

## User Requirement First (Targeted Override)
When a user's explicit requirement conflicts with the default specification:
1. Satisfy the user's explicit requirement first
2. Exempt only the conflicting check items (minimum scope)
3. Keep all other checks enabled

Recommended \`overrides.json\`:
\`\`\`json
{
  "userRequirementFirst": true,
  "allowUnsupportedStyles": ["gap"],
  "allowFontSizes": ["12px", "13px"]
}
\`\`\`
`,
  "a2ui-generation/docs/visual-interaction.md": `# Visual Interaction

## Default Visual Direction
Unless the user explicitly requests minimal, simple, plain, or understated, the default visual direction should be:
- Refined
- Beautiful
- Visually striking
- Layered
- Suited for mobile card-style presentation
- Light-background card + accent color

Do not default to "fewest components" or "lowest style cost" — actively create stronger design expression within what the protocol allows.

## Page Palette Coherence
For \`full page\` tasks, the palette should first satisfy "the whole page is one visual language" before considering whether individual sections are eye-catching enough.

Priority principles:
- Start by establishing a full-page main color band, e.g. "warm off-white base + low-saturation blue-grey accent" or "light grey-white base + golden-brown accent"
- If the \`hero\` / heading area uses dark color, it can only be used once as a clear, restrained opening — subsequent sections need a smooth return, not repeated dark-light jumps
- If the main body of the page after the hero is light-background, prefer pulling the \`hero\` into the same light-background system too, letting the image itself deliver the visual impact rather than relying on an extra large dark block
- Slight brightness changes between sections are allowed, but they should feel like layering on the same sheet of paper, not different templates stitched together
- Default to \`1\` primary accent color + \`1\` secondary accent color; do not change the main color scheme per section
- Tags, badges, route ribbons, buttons, and callouts should reuse the same accent color logic, not each go their own way

Experience rules for page mode:
- If you can immediately divide the page into "dark section", "light section", "another dark section", it is likely not cohesive
- If you ignore all image areas and look only at background colors and text colors, the page should still look like one continuous work
- \`chart\`, \`night\`, \`cta\`, and other sections that are easily made into full dark blocks: try light-background expression first; preserve a large dark block only when the user explicitly needs strong contrast or a night atmosphere requires it
- A page needs rhythm, not stacked contrast; color rhythm should be continuous, gentle, and predictable

## Real Interaction
Elements that are designed to be clickable must use real interaction by default:
- Use \`Button + functionCall\` for navigation / opening links
- Use \`Button + event\` for business actions / host integration / continued response
- Do not output fake buttons; do not let \`Text\` or plain containers pretend to be clickable

If the user has not provided a specific URL / schema / event but the design still requires a real button:
- Still output a real \`Button\` first
- A placeholder \`functionCall.openUrl\` may be used temporarily
- The \`url\` can use an obvious placeholder link, e.g. \`https://example.com/todo\`
- Do not degrade to a fake button just because a real link is missing
- The final reply must remind the user to replace with the real link, schema, or event

Button visibility safety net:
- Do not assume \`variant\` will always provide a readable background color on all renderers
- If button label text uses a light color (e.g. white), explicitly provide a dark background (e.g. \`background-color\`) on the button container, or switch to dark label text
- A button should at minimum have a clickable form: both \`padding\` and \`border-radius\` are recommended
- Before delivery, manually check: CTA label text is clearly visible against the actual background, not blending into it

## Image Sourcing
When the design requires image decoration:
- If the user's provided materials already contain usable images, prioritize making full use of them
- If the user has not provided images but the visual clearly needs them, search online for suitable real images before using them
- Do not fabricate non-existent image URLs
- If no reliable, suitable, accessible image can be found, switch to an image-free approach rather than filling in a random URL

## Anti-Patterns To Avoid
Avoid the following structures by default:
- Using a \`Text\` styled to look like a button as a CTA without a \`Button.action\`
- Turning an entry that should be clickable into explanatory text with no real event response
- Button text color relying on \`variant\` guesswork, making button labels invisible
- Adding a whole extra grey / light / host-background backing plate on the outermost layer just to make the main card stand out
- After wrapping in \`Card\`, adding another full visual shell (\`background-color + border + border-radius + drop-shadow\`) to the immediate child layer
- Each badge, icon area, metric area, and callout area inside the main card being wrapped in its own separate \`Card\`
- Making every small module into an independent mini-card for "refinement", fragmenting the visual focal point
- Mechanically turning sentence-level supporting evidence, credible corroboration, and supplementary notes into a row or column of heavy capsule blocks, causing the supporting area to steal the main focal point
- Downgrading all horizontal relationships to plain vertical stacking the moment a narrow-screen risk is perceived, sacrificing spatial tension and design quality that could otherwise hold
- Page hero is a large dark block, then it suddenly cuts to pure white, then cuts to another dark block — creating a "template-stitching" feel
- Giving \`hero\`, \`chart\`, \`night\`, \`cta\` each a completely different color palette to manufacture "premium feel"
- Tags, buttons, badges, and description blocks each using a different hue, leaving the page without a unified visual thread
- **Placing a tag group (2 or more tags) and a CTA button in the same Row — even with flex-wrap: wrap on the tag group and flex-shrink: 0 on the CTA — causing the CTA to be pushed outside the card's right boundary and clipped invisible**
`,
  "a2ui-generation/reference.md": `# A2UI Reference Index

\`reference.md\` serves as navigation only; it no longer contains the full mixed handbook.

Usage principles:
- Do not load all sub-documents at once by default
- Load only the \`1–2\` documents the current task truly needs
- For machine-verifiable rules, the [\`scripts/validate_a2ui.py\`](scripts/validate_a2ui.py) script is the authoritative source
- Default process order: run the script to validate and fix until passing, then do model review and optimization; if model review modifies files, re-run the script

## Read By Knowledge Domain

- Component protocol, fields, allowed values, style whitelist, font size spec:
  [\`docs/component-catalog.md\`](docs/component-catalog.md)
- Path binding, template binding, relative paths, list attribute binding:
  [\`docs/data-binding.md\`](docs/data-binding.md)
- DTO component mode, DTO discipline, unified function name, DTO deliverables:
  [\`docs/dto-component-mode.md\`](docs/dto-component-mode.md)
- Component/card design, height budget, content budget, multi-column text budget:
  [\`docs/component-design.md\`](docs/component-design.md)
- Page design, page-level structure, component-vs-page boundary:
  [\`docs/page-design.md\`](docs/page-design.md)
- Visual direction, interaction, buttons, image strategy, anti-patterns:
  [\`docs/visual-interaction.md\`](docs/visual-interaction.md)
- Review rounds, review checklist, human/machine validation boundary:
  [\`docs/review-validation.md\`](docs/review-validation.md)

## Read By Task

- DTO component:
  Start with [\`docs/dto-component-mode.md\`](docs/dto-component-mode.md) and [\`docs/component-design.md\`](docs/component-design.md)

- Non-DTO component:
  Start with [\`docs/component-catalog.md\`](docs/component-catalog.md) and [\`docs/component-design.md\`](docs/component-design.md)

- Non-DTO page:
  Start with [\`docs/component-catalog.md\`](docs/component-catalog.md), [\`docs/page-design.md\`](docs/page-design.md), and [\`docs/visual-interaction.md\`](docs/visual-interaction.md)

- Bug fix / review / iterating on existing files:
  Start with [\`docs/review-validation.md\`](docs/review-validation.md)

## Validation Source

Script location:
- [\`scripts/validate_a2ui.py\`](scripts/validate_a2ui.py)
`
};
