// Build script: scans src/skills/*/SKILL.md and generates src/skills/index.ts
// Usage: npx tsx scripts/generate-skills.ts

import * as fs from "fs";
import * as path from "path";

const SKILLS_DIR = path.resolve(__dirname, "../src/skills");
const OUTPUT_FILE = path.join(SKILLS_DIR, "index.ts");

interface SkillEntry {
  name: string;
  content: string;
  /** Additional markdown files from docs/ subdirectory, keyed by relative path */
  docs: Record<string, string>;
}

function parseFrontmatterName(content: string, fallback: string): string {
  const normalized = content.replace(/\r\n/g, "\n").replace(/\r/g, "\n");
  if (!normalized.startsWith("---")) return fallback;
  const endIndex = normalized.indexOf("\n---", 3);
  if (endIndex === -1) return fallback;
  const yaml = normalized.slice(3, endIndex);
  for (const line of yaml.split("\n")) {
    const colonIndex = line.indexOf(":");
    if (colonIndex === -1) continue;
    const key = line.slice(0, colonIndex).trim();
    if (key === "name") {
      let value = line.slice(colonIndex + 1).trim();
      if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
        value = value.slice(1, -1);
      }
      return value;
    }
  }
  return fallback;
}

function discoverSkills(): SkillEntry[] {
  const entries = fs.readdirSync(SKILLS_DIR, { withFileTypes: true });
  const skills: SkillEntry[] = [];

  for (const entry of entries) {
    if (!entry.isDirectory()) continue;
    const skillMdPath = path.join(SKILLS_DIR, entry.name, "SKILL.md");
    if (!fs.existsSync(skillMdPath)) continue;

    const content = fs.readFileSync(skillMdPath, "utf-8");
    const name = parseFrontmatterName(content, entry.name);

    // Discover additional .md files (reference.md, docs/*.md)
    const docs: Record<string, string> = {};
    const skillDir = path.join(SKILLS_DIR, entry.name);
    collectMarkdownFiles(skillDir, "", docs);

    skills.push({ name, content, docs });
  }

  return skills.sort((a, b) => a.name.localeCompare(b.name));
}

function collectMarkdownFiles(baseDir: string, prefix: string, result: Record<string, string>): void {
  const entries = fs.readdirSync(path.join(baseDir, prefix), { withFileTypes: true });
  for (const entry of entries) {
    const relPath = prefix ? `${prefix}/${entry.name}` : entry.name;
    if (entry.isDirectory()) {
      collectMarkdownFiles(baseDir, relPath, result);
    } else if (entry.name.endsWith(".md") && entry.name !== "SKILL.md") {
      const fullPath = path.join(baseDir, relPath);
      result[relPath] = fs.readFileSync(fullPath, "utf-8");
    }
  }
}

function escapeTemplateLiteral(str: string): string {
  return str.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$/g, "\\$");
}

function generateIndex(skills: SkillEntry[]): string {
  const entries = skills.map((s) => {
    const docEntries = Object.entries(s.docs);
    if (docEntries.length === 0) {
      return `  "${s.name}": \`${escapeTemplateLiteral(s.content)}\``;
    }
    // Include docs as a separate structure
    const docLines = docEntries
      .map(([key, val]) => `    "${key}": \`${escapeTemplateLiteral(val)}\``)
      .join(",\n");
    return `  "${s.name}": \`${escapeTemplateLiteral(s.content)}\``;
  });

  // Generate bundled docs map for multi-file skills
  const docSkills = skills.filter((s) => Object.keys(s.docs).length > 0);
  const docEntries: string[] = [];
  for (const s of docSkills) {
    for (const [key, val] of Object.entries(s.docs)) {
      docEntries.push(`  "${s.name}/${key}": \`${escapeTemplateLiteral(val)}\``);
    }
  }

  const lines = [
    "// Auto-generated by scripts/generate-skills.ts — do not edit",
    "",
    "export const bundledSkills: Record<string, string> = {",
    entries.join(",\n"),
    "};",
  ];

  if (docEntries.length > 0) {
    lines.push("", "export const bundledSkillDocs: Record<string, string> = {");
    lines.push(docEntries.join(",\n"));
    lines.push("};");
  }

  lines.push("");
  return lines.join("\n");
}

// Main
const skills = discoverSkills();

if (skills.length === 0) {
  console.error("No skills found in", SKILLS_DIR);
  process.exit(1);
}

const output = generateIndex(skills);
fs.writeFileSync(OUTPUT_FILE, output, "utf-8");

console.log(`Generated ${OUTPUT_FILE} with ${skills.length} skills:`);
for (const s of skills) {
  console.log(`  - ${s.name}`);
}
